name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      # Cache dependencies
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: sudo composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      # Install Node.js and NPM dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust version if needed

      - name: Install NPM dependencies
        run: sudo npm install

      - name: Build assets
        run: sudo npm run prod

      # Create .env file from GitHub secret
      - name: Create .env file from secret
        run: |
          echo "${{ secrets.LARAVEL_ENV }}" > .env
        shell: bash

      # Run Laravel key generate
      - name: Generate app key
        run: sudo php artisan key:generate

      # Run Laravel migrations
      - name: Run migrations
        run: sudo php artisan migrate --force

      # Restart Nginx and PHP-FPM (adjust these commands if needed)
      - name: Restart Nginx and PHP-FPM
        run: |
          sudo systemctl restart nginx
          sudo systemctl restart php8.2-fpm
