name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Reset permissions on the /var/www/html/project directory
      - name: Reset permissions on project directory
        run: sudo chown -R $(whoami):$(whoami) /var/www/html/project

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /var/www/html/project  # Ensure the code is checked out in the correct directory

      # Set up PHP 8.2
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          cd /var/www/html/project
          sudo composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      # Install Node.js and NPM
      - name: Install Node.js and NPM
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install NPM dependencies
        run: |
          cd /var/www/html/project
          sudo npm install

      - name: Build assets
        run: |
          cd /var/www/html/project
          sudo npm run build

      # Create .env file manually with basic contents
      - name: Create .env file
        run: |
          cd /var/www/html/project
          echo "APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost

          LOG_CHANNEL=stack

          DB_CONNECTION=mysql
          DB_HOST=localhost
          DB_PORT=3306
          DB_DATABASE=awp
          DB_USERNAME=localhost
          DB_PASSWORD=" > .env

      - name: Generate app key
        run: |
          cd /var/www/html/project
          sudo php artisan key:generate

      # Run migrations
      - name: Run migrations
        run: |
          cd /var/www/html/project
          sudo php artisan migrate --force

      - name: Restart Nginx and PHP-FPM
        run: |
          sudo systemctl restart nginx
          sudo systemctl restart php8.2-fpm
