name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Reset permissions on the Laravel-CRUD directory before checking out code
      - name: Reset permissions on public/build/assets
        run: sudo chown -R $(whoami) /home/ubuntu/actions-runner/_work/Laravel-CRUD/Laravel-CRUD/public/build/assets

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP 8.2
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: sudo composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      # Install Node.js and NPM
      - name: Install Node.js and NPM
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install NPM dependencies
        run: sudo npm install

      - name: Build assets
        run: sudo npm run build

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.LARAVEL_ENV }}" > .env
        shell: bash

      - name: Generate app key
        run: sudo php artisan key:generate

      - name: Run migrations
        run: sudo php artisan migrate --force

      - name: Restart Nginx and PHP-FPM
        run: |
          sudo systemctl restart nginx
          sudo systemctl restart php8.2-fpm
